version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15673:15672"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:15672/api/healthchecks/node || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit consumer_timeout 432000000"
