version: '3.8'

services:
  nougat_api_server:
    image: nougat_api_server:latest
    ports:
      - "8403-8405:8503"
    networks:
      - my_network
    volumes:
      - /home/developer/prakash/nougat:/bud-nougat
    healthcheck:
      test: wget --no-verbose -O /dev/null --tries=1 http://localhost:8503/ || exit 1
      interval: 10s
      timeout: 5s
      start_period: 30s
    deploy:
      replicas: 3
      resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0', '1', '2']
                capabilities: [gpu]
  
  # producer:
  #   image: pdf-pipeline:latest
  #   working_dir: /src
  #   command: python3 -m pdf_pipeline.pdf_producer
  #   networks:
  #     - my_network
  #   volumes:
  #     - /home/developer/prakash/pdf_extraction_pipeline:/src
  #   depends_on:
  #     nougat_api_server:
  #       condition: service_healthy
  #     # nougat_api_server_2:
  #     #   condition: service_healthy

  consumer:
    image: pdf-pipeline:latest
    working_dir: /src
    command: python3 -m pdf_pipeline.pdf_consumer
    networks:
      - my_network
    volumes:
      - /home/developer/prakash/pdf_extraction_pipeline:/src
    depends_on:
      nougat_api_server:
        condition: service_healthy
      # nougat_api_server_2:
        # condition: service_healthy
    deploy:
      replicas: 8

  ptm:
    image: pdf-pipeline:latest
    working_dir: /src
    command: python3 -m pdf_pipeline.ptm_consumer
    networks:
      - my_network
    volumes:
      - /home/developer/prakash/pdf_extraction_pipeline:/src
    depends_on:
      nougat_api_server:
        condition: service_healthy
      # nougat_api_server_2:
      #   condition: service_healthy
    deploy:
      replicas: 8
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

  ptm2:
    image: pdf-pipeline:latest
    working_dir: /src
    command: python3 -m pdf_pipeline.ptm_consumer
    networks:
      - my_network
    volumes:
      - /home/developer/prakash/pdf_extraction_pipeline:/src
    depends_on:
      nougat_api_server:
        condition: service_healthy
      # nougat_api_server_2:
      #   condition: service_healthy
    deploy:
      replicas: 8
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2']
              capabilities: [gpu]

  check_ptm:
    image: pdf-pipeline:latest
    working_dir: /src
    command: python3 -m pdf_pipeline.check_ptm_consumer
    networks:
      - my_network
    volumes:
      - /home/developer/prakash/pdf_extraction_pipeline:/src
    depends_on:
      nougat_api_server:
        condition: service_healthy
      # nougat_api_server_2:
      #   condition: service_healthy
    deploy:
      replicas: 12

  other_pages:
    image: pdf-pipeline:latest
    working_dir: /src
    command: python3 -m pdf_pipeline.other_pages_consumer
    networks:
      - my_network
    volumes:
      - /home/developer/prakash/pdf_extraction_pipeline:/src
    depends_on:
      nougat_api_server:
        condition: service_healthy
      # nougat_api_server_2:
      #   condition: service_healthy
    deploy:
      replicas: 4
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '2']
              capabilities: [gpu]

  text_pages:
    image: pdf-pipeline:latest
    working_dir: /src
    command: python3 -m pdf_pipeline.text_pages_consumer
    networks:
      - my_network
    volumes:
      - /home/developer/prakash/pdf_extraction_pipeline:/src
    depends_on:
      nougat_api_server:
        condition: service_healthy
      # nougat_api_server_2:
      #   condition: service_healthy
    deploy:
      replicas: 12

  latex_pages:
    image: pdf-pipeline:latest
    working_dir: /src
    command: python3 -m pdf_pipeline.latex_ocr_consumer
    networks:
      - my_network
    volumes:
      - /home/developer/prakash/pdf_extraction_pipeline:/src
    depends_on:
      nougat_api_server:
        condition: service_healthy
      # nougat_api_server_2:
      #   condition: service_healthy
    deploy:
      replicas: 3
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '2']
              capabilities: [gpu]

  nougat_pages:
    image: pdf-pipeline:latest
    working_dir: /src
    command: python3 -m pdf_pipeline.nougat_consumer "http://nougat_api_server:8503/predict/"
    networks:
      - my_network
    volumes:
      - /home/developer/prakash/pdf_extraction_pipeline:/src
    depends_on:
      nougat_api_server:
        condition: service_healthy
    deploy:
      replicas: 3

  bud_ocr:
    image: pdf-pipeline:latest
    working_dir: /src
    command: python3 -m pdf_pipeline.bud_ocr_consumer
    networks:
      - my_network
    volumes:
      - /home/developer/prakash/pdf_extraction_pipeline:/src
    depends_on:
      nougat_api_server:
        condition: service_healthy
      # nougat_api_server_2:
      #   condition: service_healthy
    deploy:
      replicas: 1

  book_completion:
    image: pdf-pipeline:latest
    working_dir: /src
    command: python3 -m pdf_pipeline.book_completion_consumer
    networks:
      - my_network
    volumes:
      - /home/developer/prakash/pdf_extraction_pipeline:/src
    depends_on:
      nougat_api_server:
        condition: service_healthy
      # nougat_api_server_2:
      #   condition: service_healthy
    deploy:
      replicas: 12

# volumes:
#   my_volume:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '/home/azureuser/prakash/pdf_extraction_pipeline'

networks:
  my_network:
